//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jumper
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistiryChangesMaterials
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> MaterialId { get; set; }
    
        public virtual Materials Materials { get; set; }
    }
}
