//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jumper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.HistiryChangesAgentCost = new HashSet<HistiryChangesAgentCost>();
            this.HistiryChangesMaterials = new HashSet<HistiryChangesMaterials>();
            this.Materials1 = new HashSet<Materials>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> MaterialsTypeId { get; set; }
        public Nullable<int> PostavshikId { get; set; }
        public Nullable<int> CountInPacket { get; set; }
        public Nullable<int> UnitMeasurementId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> MinCount { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<int> Cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistiryChangesAgentCost> HistiryChangesAgentCost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistiryChangesMaterials> HistiryChangesMaterials { get; set; }
        public virtual Postavshiks Postavshiks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materials> Materials1 { get; set; }
        public virtual Materials Materials2 { get; set; }
        public virtual UnitMeasurements UnitMeasurements { get; set; }
    }
}
