//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jumper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JumperEntities : DbContext
    {
        public JumperEntities()
            : base("name=JumperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agents> Agents { get; set; }
        public virtual DbSet<AgentTypes> AgentTypes { get; set; }
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<ApplicationStatuses> ApplicationStatuses { get; set; }
        public virtual DbSet<Deliverys> Deliverys { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<HistiryChangesAgentCost> HistiryChangesAgentCost { get; set; }
        public virtual DbSet<HistiryChangesMaterials> HistiryChangesMaterials { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<MaterialsType> MaterialsType { get; set; }
        public virtual DbSet<NFCEmployee> NFCEmployee { get; set; }
        public virtual DbSet<Postavshiks> Postavshiks { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductTypes> ProductTypes { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TimeDoor> TimeDoor { get; set; }
        public virtual DbSet<UnitMeasurements> UnitMeasurements { get; set; }
    }
}
