//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jumper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Id { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public string ProductName { get; set; }
        public string Artikyl { get; set; }
        public Nullable<int> PeopleCount { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> AgentCost { get; set; }
        public Nullable<int> Wight { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Lenght { get; set; }
        public Nullable<int> WeightWithoutPacket { get; set; }
        public Nullable<int> WeightWithPacket { get; set; }
        public string NumberStandart { get; set; }
    
        public virtual Agents Agents { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
    }
}
